name: 'NR1 Installation'

on:
  workflow_dispatch:
    
jobs:
  nr1Install:
    name: 'NR1 Install'
    runs-on: ubuntu-latest
    
    steps:
    - name: Checkout
      uses: actions/checkout@v3

    - name: Install NR1 CLI
      run: |
        echo "Hello"
        # curl -s https://cli.nr-ext.net/installer.sh | sudo bash
        # nr1 --version
        # nr1 profiles:add --name account-3628623 --api-key NRAK-TZ3U65WTWUB4MG8HD02ON9S7OXF --region us
        # nr1 create --type visualization --name visualization1

    - name: Get Previous Workflow Run
      if: always()
      id: get_run
      run: |
        # Get the previous workflow run information using the GitHub API
        PREVIOUS_RUN=$(curl -s -H "Authorization: Bearer ${{ secrets.GIT_TOKEN }}" \
          "https://api.github.com/repos/${{ github.repository }}/actions/runs?event=workflow_dispatch" | jq -r '.workflow_runs[1]')

        # Extract the status of the previous run
        echo "PREVIOUS_STATUS=$(echo "$PREVIOUS_RUN" | jq -r '.conclusion')" >> $GITHUB_OUTPUT

        # echo "Previous Workflow Status: $PREVIOUS_STATUS"
        
    
      
      
      
#     - name: NR1 CLI version
#       run: nr1 --version | sudo bash
      
#     - name: NR1 Nerdpack Build
#       run: |
#         nr1 nerdpack:build
#         nr1 nerdpack:validate
        
#     - name: Install NR1 CLI
#       if: env.SUBMODULE_NAME != ''
#       run: |
#         curl -s https://cli.nr-ext.net/installer.sh | sudo bash
#         nr1 profiles:add --name nr1-apps-us --api-key ${{ secrets.NR1_APPS_KEY_US }} --region us
# nr1 profiles:add --name account-3628623 --api-key NRAK-TZ3U65WTWUB4MG8HD02ON9S7OXF --region us

 
