name: 'NR1 Installation'

on:
  workflow_dispatch:
    
jobs:
  tfapply:
    name: 'NR1 Install'
    runs-on: ubuntu-latest
    
    steps:
    - name: Checkout
      uses: actions/checkout@v3

    - name: Install NR1 CLI
      run: curl -s https://cli.nr-ext.net/installer.sh | sudo bash
      
    - name: NR1 CLI version
      run: nr1 --version | sudo bash
      
    - name: NR1 Nerdpack Build
      run: |
        nr1 nerdpack:build
        nr1 nerdpack:validate

  
 
