name: Trial Pipeline
on:
  workflow_dispatch:
    # inputs:
    #    Revisionversion:
    #       description: 'CURL Revision version'
    #       required: true
    #       default: '2'
    #    kube_deploy_delete:
    #       description: 'kube_deploy_delete'
    #       required: true
    #       default: 'yes'
    


jobs:
  testcases:
    runs-on: ubuntu-latest
    env:
      username: "atulpandey108"
      image_name_2: "carts"
    
    steps:
    - uses: actions/checkout@v3

    - name: print statement
      run: echo "HEllo"

  newjob:
    runs-on: ubuntu-latest
    needs: testcases
    if: always()
    steps: 
    - uses: actions/checkout@v3
  
    - name: Get Previous Workflow Run
      if: always()
      id: get_run
      run: |
        curl -L \
        -H "Accept: application/vnd.github+json" \
        -H "Authorization: Bearer ${{ secrets.GIT_TOKEN }}" \
        -H "X-GitHub-Api-Version: 2022-11-28" \
        https://api.github.com/repos/${{ github.repository }}/actions/workflows/Trial Pipeline/runs
